import fs from 'fs/promises';
import { constants } from 'fs';
import { SUPPORTED_HATS, HatProfile } from '../types/hats';

const CONFIG_PATH = process.env.CONFIG_PATH || '/boot/firmware/config.txt';

export class ConfigService {

  async checkPermissions(): Promise<boolean> {
    try {
      await fs.access(CONFIG_PATH, constants.W_OK);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Versucht anhand der config.txt zu erraten, was aktuell konfiguriert ist
   */
  async getActiveConfig(): Promise<HatProfile | null> {
    try {
      const content = await fs.readFile(CONFIG_PATH, 'utf-8');
      
      for (const hat of Object.values(SUPPORTED_HATS)) {
        if (hat.id === 'none' || hat.id === 'usb-dac') continue;
        
        // Prüfen ob Overlay aktiv (nicht auskommentiert)
        const regex = new RegExp(`^\\s*${hat.overlay}`, 'm');
        if (regex.test(content)) {
          return hat;
        }
      }
      return SUPPORTED_HATS['none'];
    } catch (error) {
      console.error('Fehler beim Lesen der Config:', error);
      return null;
    }
  }

  /**
   * Prüft ob force_eeprom_read=0 gesetzt ist
   */
  async isEepromReadDisabled(): Promise<boolean> {
    try {
      const content = await fs.readFile(CONFIG_PATH, 'utf-8');
      return content.includes('force_eeprom_read=0');
    } catch {
      return false;
    }
  }

  /**
   * Schreibt die neue Konfiguration in die config.txt
   */
  async setHat(hatId: string): Promise<void> {
    const targetHat = SUPPORTED_HATS[hatId];
    if (!targetHat) throw new Error('Invalid HAT ID');

    let content = await fs.readFile(CONFIG_PATH, 'utf-8');
    const lines = content.split('\n');
    const newLines: string[] = [];

    // 1. Alte Konfiguration bereinigen
    for (const line of lines) {
      let keepLine = true;
      
      // Entferne existierende HiFiBerry und IQaudIO overlays
      if (line.trim().startsWith('dtoverlay=hifiberry') || line.trim().startsWith('dtoverlay=iqaudio')) {
        keepLine = false;
      }
      
      // Entferne Onboard Audio Settings, um Konflikte zu vermeiden
      if (line.trim().startsWith('dtparam=audio=')) {
        newLines.push('# ' + line); // Auskommentieren statt löschen
        keepLine = false;
      }

      // Entferne unsere eigenen Markierungen von früher
      if (line.includes('BEATNIK AUDIO CONFIGURATION')) keepLine = false;

      if (keepLine) newLines.push(line);
    }

    // 2. Neuen Block hinzufügen
    newLines.push('');
    newLines.push('############################');
    newLines.push('# BEATNIK AUDIO CONFIGURATION');
    newLines.push('# Automatically generated by beatnik-hardware-service');
    
    if (hatId !== 'none' && hatId !== 'usb-dac') {
        newLines.push(targetHat.overlay);
        // Onboard Audio aus, wenn HAT genutzt wird
        newLines.push('dtparam=audio=off');
    } else {
        // Onboard Audio an, wenn kein HAT
        newLines.push('dtparam=audio=on');
    }
    
    newLines.push('############################');
    newLines.push('');

    // Leere Zeilen am Ende trimmen
    const finalContent = newLines.join('\n').replace(/\n{3,}/g, '\n\n');
    await fs.writeFile(CONFIG_PATH, finalContent, 'utf-8');
  }
}